CREATE ROLE guest_user WITH LOGIN PASSWORD 'guest_password';
GRANT CONNECT ON DATABASE store TO guest_user;
GRANT USAGE ON SCHEMA public TO guest_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO guest_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO guest_user;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC;
GRANT EXECUTE ON FUNCTION search_item_by_name(TEXT) TO guest_user;
